- os: linux
  dist: bionic
  env: TOOL=docs
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - cmake
        - libgsl-dev 
        - libeigen3-dev 
        - libnlopt-dev
        - doxygen
        - doxygen-doc
        - doxygen-latex
        - doxygen-gui
        - graphviz
        
  script:
   - mkdir build && cd build
   - cmake -DUseLibCMAES=OFF ..
   - make
        
  if: branch = master
  deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_API_TOKEN
    local_dir: build/html
