name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build && cd build && cmake -DUseLibCMAES=OFF .. 
    - name: make
      run: make
