name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : installPackages
      run : npm install @actions/toolcache-boost-ubuntu-1804-x64@1.69.1579706608 && sudo apt-get install --no-install-recommends --yes libgsl-dev libeigen3-dev libnlopt-dev
    - name: cmake
      run: mkdir build && cd build && cmake -DUseLibCMAES=OFF .. 
    - name: make
      run: cd build && make
